name: "CI"
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  ci:
    name: "Run CI"
    strategy:
      fail-fast: false
      matrix:
        go: ["1.16.x", "1.17.x"]
    env:
      CI_CACHE: v1
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - uses: actions/cache@v2
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ env.CI_CACHE }}-${{ matrix.go }}-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ env.CI_CACHE }}-${{ matrix.go }}-
      - uses: WillAbides/setup-go-faster@v1.7.0
        with:
          go-version: ${{ matrix.go }}
      - run: "go test ./..."
      - run: "go vet ./..."
      - uses: dominikh/staticcheck-action@v1.1.0
        with:
          version: "2021.1.1"
          install-go: false
          cache-key: ${{ matrix.go }}
